# services

FROM centos:7.4.1708
#MAINTAINER
#LABEL 

#
# build time argument
# TENANT_URL: tenant URL
ARG TENANT_URL

#
# environment variables
# CODE: enrollment code
# LOGIN_ROLE: roles that can login

# the following variables are optional
# PORT: SSH port (default: 22)
# NAME: name of system
# ADDRESS: address of system
# CONNECTOR: connector to use
# ROOT_PASSWORD: password for root (used when not vaulting root password)
# OPTION: optional parameters for cenroll command

# fill in the correct values for the followings
# note that they can be set in docker run command
ENV CODE="" PORT="" NAME="" ADDRESS="" CONNECTOR="" LOGIN_ROLE="" 
ENV OPTION="" ROOT_PASSWORD=""
ENV URL $TENANT_URL
# set to Yes if you want to enable "Use My Account" feature
ENV ENABLE_USE_MY_ACCOUNT ""
# set to Yes if you want to let Centrify Privileged Access Service to store the root password
ENV VAULT_ROOT_PASSWD ""
# roles that can login as root
ENV LOGIN_AS_ROOT_ROLES ""
# set to Yes if you want to let Centrify Privileged Access Service to manage the root password
ENV MANAGE_ROOT_PASSWD ""

STOPSIGNAL SIGRTMIN+3

# sshd setup
RUN yum -y update && yum install -y openssh-server vim openssh-clients \
    && mkdir /var/run/sshd \
    && ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N '' \
    && sed -i '/^#\?PermitRootLogin/c\PermitRootLogin yes' /etc/ssh/sshd_config \
    && sed -i '/^#\?ChallengeResponseAuthentication/c\ChallengeResponseAuthentication yes' /etc/ssh/sshd_config \
    && sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd \
    && yum -y install systemd && yum clean all
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done ); 

VOLUME [ "/sys/fs/cgroup" ]

# note that systemd comes with journald in CentOS...no need to install rsyslog

# enable and start services
RUN systemctl enable sshd.service

# download and install Centrify Agent
RUN curl --fail -s -o /tmp/CentrifyCC-rhel6.x86_64.rpm https://edge.centrify.com/products/cloud-service/CliDownload/Centrify/CentrifyCC-rhel6.x86_64.rpm \
   && yum -y install /tmp/CentrifyCC-rhel6.x86_64.rpm && yum clean all

# create a new service for unenroll Centrify agent
COPY centrifycc-unenroll.service /usr/lib/systemd/system/centrifycc-unenroll.service
RUN systemctl enable centrifycc-unenroll.service

# note that the selinux policy set to enforcing
# change to permissive for now

RUN sed -i 's/SELINUX=enforcing/SELINUX=permissive/g' /etc/selinux/config

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

COPY ./cjoin_startup.sh /tmp/cjoin_startup.sh
RUN chmod 500 /tmp/cjoin_startup.sh

EXPOSE 22

CMD ["/tmp/cjoin_startup.sh"]

